spring:
  profiles:
    active: dev

#system
server:
  tomcat:
    basedir: /data/layku/temp/
  servlet:
    session:
      timeout: 18000

#logback
logging:
  config: classpath:config/logback-spring.xml